# Generated by Django 2.1.5 on 2019-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=1500)),
                ('add', models.CharField(max_length=1000)),
                ('last_date', models.DateField()),
                ('mobileno', models.IntegerField(default=999999999)),
            ],
        ),
    ]
