# Generated by Django 2.1.5 on 2019-03-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='image1model',
            name='user',
            field=models.ForeignKey(default=None, on_delete=None, to='Image_Gallary2.UserInfo1Model'),
        ),
    ]
