# Generated by Django 2.1.5 on 2019-03-31 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Gallary2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/Image_Gallary2', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='image1model',
            name='user',
        ),
        migrations.RenameModel(
            old_name='UserInfo1Model',
            new_name='UserInfoModel',
        ),
        migrations.DeleteModel(
            name='Image1Model',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=None, to='Image_Gallary2.UserInfoModel'),
        ),
    ]
