# Generated by Django 2.1.5 on 2019-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPT_Gallary', '0002_auto_20190403_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pptmodel',
            name='ppt',
            field=models.FileField(blank=True, upload_to='ppt/', verbose_name='PPT'),
        ),
    ]
