# Generated by Django 2.1.5 on 2019-03-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Gallary1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('img1', models.ImageField(blank=True, upload_to='images/Image_Gallary1')),
                ('img2', models.ImageField(blank=True, upload_to='images/Image_Gallary1')),
                ('img3', models.ImageField(blank=True, upload_to='images/Image_Gallary1')),
                ('img4', models.ImageField(blank=True, upload_to='images/Image_Gallary1')),
                ('img5', models.ImageField(blank=True, upload_to='images/Image_Gallary1')),
            ],
        ),
    ]
