# Generated by Django 2.1.5 on 2019-03-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Gallary1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image_Gallary1Model',
            new_name='Image_GallaryModel',
        ),
    ]
