# Generated by Django 2.1.5 on 2019-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('mobileno', models.IntegerField(default=999999999)),
                ('add', models.CharField(max_length=1000)),
                ('stars', models.FloatField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
